#!/usr/bin/env python3
"""
Generate .vitepress/config.mjs from the converted Markdown tree.

Each top-level subfolder of vitepress/ becomes a collapsible sidebar group;
all groups are shown globally so the sidebar acts as a site-wide table of contents.
"""
from __future__ import annotations
import sys
from pathlib import Path
import json

ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("vitepress")
CONFIG = ROOT / ".vitepress" / "config.mjs"

CATEGORIES = sorted(
    p.name for p in ROOT.iterdir()
    if p.is_dir() and not p.name.startswith('.') and p.name != 'node_modules'
)

TOP_LEVEL_PAGES = sorted(
    f for f in ROOT.glob('*.md')
    if f.name not in ('index.md',)
)


def page_link(p: Path, root: Path) -> str:
    rel = p.relative_to(root).with_suffix('')
    return '/' + str(rel).replace('\\', '/')


def sidebar_global() -> list[dict]:
    groups: list[dict] = []
    # Top-level pages (README, python-new-py3)
    if TOP_LEVEL_PAGES:
        items = []
        for f in TOP_LEVEL_PAGES:
            title = f.stem.replace('-', ' ').replace('_', ' ').title()
            items.append({'text': title, 'link': page_link(f, ROOT)})
        groups.append({
            'text': 'General',
            'collapsible': True,
            'collapsed': True,
            'items': items,
        })
    # Category groups
    for cat in CATEGORIES:
        catdir = ROOT / cat
        files = sorted(catdir.glob('*.md'))
        items = []
        for f in files:
            if f.name == 'index.md':
                items.insert(0, {'text': 'Overview', 'link': f'/{cat}/'})
                continue
            title = f.stem.replace('-', ' ').replace('_', ' ').title()
            items.append({'text': title, 'link': page_link(f, ROOT)})
        groups.append({
            'text': cat.replace('-', ' ').title(),
            'collapsible': True,
            'collapsed': True,
            'items': items,
        })
    return groups


def nav_entries() -> list[dict]:
    return []


def render_config() -> str:
    cfg = {
        'title': 'Pysheeet',
        'description': 'Python cheat sheets',
        'cleanUrls': True,
        'themeConfig': {
            'logo': '/logo.svg',
            'nav': nav_entries(),
            'sidebar': sidebar_global(),
            'search': {'provider': 'local'},
            'outline': {'level': [2, 3]},
            'docFooter': {'prev': 'Previous', 'next': 'Next'},
        },
    }
    body = json.dumps(cfg, indent=2)
    return (
        f"// Auto-generated by gen-config.py — do not edit by hand.\n"
        f"// Regenerate with: python3 gen-config.py vitepress\n\n"
        f"export default {body};\n"
    )


def main() -> int:
    CONFIG.parent.mkdir(parents=True, exist_ok=True)
    CONFIG.write_text(render_config(), encoding='utf-8')
    print(f'wrote {CONFIG}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
