#!/usr/bin/env python3
"""
Generate .vitepress/config.mjs from the converted Markdown tree.

Each top-level subfolder of vitepress/ becomes a sidebar group;
the page order is alphabetical (VitePress will sort by file name).
Top-level .md files (except index.md) become nav entries.
"""
from __future__ import annotations
import sys
from pathlib import Path
import json

ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("vitepress")
CONFIG = ROOT / ".vitepress" / "config.mjs"

CATEGORIES = sorted(
    p.name for p in ROOT.iterdir()
    if p.is_dir() and not p.name.startswith('.') and p.name != 'node_modules'
)


def page_link(p: Path, root: Path) -> str:
    rel = p.relative_to(root).with_suffix('')
    return '/' + str(rel).replace('\\', '/')


def sidebar_for(category: str) -> list[dict]:
    catdir = ROOT / category
    files = sorted(catdir.glob('*.md'))
    items: list[dict] = []
    for f in files:
        if f.name == 'index.md':
            continue
        title = f.stem.replace('-', ' ').replace('_', ' ').title()
        items.append({'text': title, 'link': page_link(f, ROOT)})
    return items


def nav_entries() -> list[dict]:
    nav = [{'text': 'Home', 'link': '/'}]
    top_level = sorted(ROOT.glob('*.md'))
    for f in top_level:
        if f.name in ('index.md',):
            continue
        title = f.stem.replace('-', ' ').replace('_', ' ').title()
        nav.append({'text': title, 'link': page_link(f, ROOT)})
    for cat in CATEGORIES:
        title = cat.replace('-', ' ').title()
        nav.append({'text': title, 'link': f'/{cat}/'})
    return nav


def render_config() -> str:
    sidebar = {f'/{cat}/': [{'text': 'Overview', 'link': f'/{cat}/'}, *sidebar_for(cat)] for cat in CATEGORIES}
    cfg = {
        'title': 'Pysheeet',
        'description': 'Python cheat sheets',
        'cleanUrls': True,
        'nav': nav_entries(),
        'sidebar': sidebar,
        'search': {'provider': 'local'},
        'outline': {'level': [2, 3]},
    }
    body = json.dumps(cfg, indent=2)
    return (
        f"// Auto-generated by gen-config.py — do not edit by hand.\n"
        f"// Regenerate with: python3 gen-config.py vitepress\n\n"
        f"export default {body};\n"
    )


def main() -> int:
    CONFIG.parent.mkdir(parents=True, exist_ok=True)
    CONFIG.write_text(render_config(), encoding='utf-8')
    print(f'wrote {CONFIG}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
