#!/usr/bin/env python3
"""
Generate .vitepress/config.mjs from the converted Markdown tree.

Each top-level subfolder of vitepress/ becomes a collapsible sidebar group;
all groups are shown globally so the sidebar acts as a site-wide table of contents.
"""
from __future__ import annotations
import sys
from pathlib import Path
import json

ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("vitepress")
CONFIG = ROOT / ".vitepress" / "config.mjs"

CATEGORY_ORDER = [
    'interview', 'basic', 'os', 'concurrency', 'asyncio',
    'network', 'database', 'security', 'extension', 'llm', 'hpc',
    'appendix',
]

FILE_ORDER: dict[str, list[str]] = {
    'basic': [
        'python-basic', 'python-future', 'python-func', 'python-object',
        'python-typing', 'python-list', 'python-set', 'python-dict',
        'python-heap', 'python-generator', 'python-unicode', 'python-rexp',
    ],
    'os': [
        'python-date', 'python-os', 'python-io',
    ],
    'concurrency': [
        'python-threading', 'python-multiprocessing', 'python-futures',
    ],
    'asyncio': [
        'python-asyncio-guide', 'python-asyncio-basic',
        'python-asyncio-server', 'python-asyncio-advanced',
    ],
    'network': [
        'python-socket', 'python-socket-server', 'python-socket-async',
        'python-socket-ssl', 'python-socket-sniffer', 'python-ssh',
    ],
    'database': [
        'python-sqlalchemy', 'python-sqlalchemy-orm', 'python-sqlalchemy-query',
    ],
    'security': [
        'python-crypto', 'python-tls', 'python-vulnerability',
    ],
    'extension': [
        'python-ctypes', 'python-capi', 'python-cext-modern', 'cpp-from-python',
    ],
    'llm': [
        'pytorch', 'megatron', 'llm-serving', 'llm-bench',
    ],
    'hpc': [
        'slurm', 'ray',
    ],
    'appendix': [
        'nvshmem-multi-nic', 'disaggregated-prefill-decode',
        'megatron-efa-monitoring', 'nccl-gin',
        'python-walrus', 'python-gdb',
    ],
}

CATEGORIES = [p.name for p in ROOT.iterdir()
              if p.is_dir() and not p.name.startswith('.') and p.name != 'node_modules'
              and p.name in CATEGORY_ORDER]

CATEGORIES.sort(key=lambda c: CATEGORY_ORDER.index(c))

TOP_LEVEL_PAGES = [f for f in ROOT.glob('*.md')
                   if f.name not in ('index.md',)]


def page_link(p: Path, root: Path) -> str:
    rel = p.relative_to(root).with_suffix('')
    return '/' + str(rel).replace('\\', '/')


def sort_files(files: list[Path], cat: str) -> list[Path]:
    order = FILE_ORDER.get(cat, [])
    if not order:
        return sorted(files)
    def sort_key(f: Path) -> int:
        stem = f.stem
        try:
            return order.index(stem)
        except ValueError:
            return len(order)
    return sorted(files, key=sort_key)


def sidebar_global() -> list[dict]:
    groups: list[dict] = []
    # Top-level pages (README, python-new-py3)
    if TOP_LEVEL_PAGES:
        items = []
        for f in TOP_LEVEL_PAGES:
            title = f.stem.replace('-', ' ').replace('_', ' ').title()
            items.append({'text': title, 'link': page_link(f, ROOT)})
        groups.append({
            'text': 'General',
            'collapsible': True,
            'collapsed': True,
            'items': items,
        })
    # Category groups
    for cat in CATEGORIES:
        catdir = ROOT / cat
        files = sort_files(list(catdir.glob('*.md')), cat)
        items = []
        for f in files:
            if f.name == 'index.md':
                items.insert(0, {'text': 'Overview', 'link': f'/{cat}/'})
                continue
            title = f.stem.replace('-', ' ').replace('_', ' ').title()
            items.append({'text': title, 'link': page_link(f, ROOT)})
        groups.append({
            'text': cat.replace('-', ' ').title(),
            'collapsible': True,
            'collapsed': True,
            'items': items,
        })
    return groups


def nav_entries() -> list[dict]:
    return []


def render_config() -> str:
    cfg = {
        'title': 'Pysheeet',
        'description': 'Python cheat sheets',
        'cleanUrls': True,
        'themeConfig': {
            'logo': '/logo.svg',
            'nav': nav_entries(),
            'sidebar': sidebar_global(),
            'search': {'provider': 'local'},
            'outline': {'level': [2, 3]},
            'docFooter': {'prev': 'Previous', 'next': 'Next'},
        },
    }
    body = json.dumps(cfg, indent=2)
    return (
        f"// Auto-generated by gen-config.py — do not edit by hand.\n"
        f"// Regenerate with: python3 gen-config.py vitepress\n\n"
        f"export default {body};\n"
    )


def main() -> int:
    CONFIG.parent.mkdir(parents=True, exist_ok=True)
    CONFIG.write_text(render_config(), encoding='utf-8')
    print(f'wrote {CONFIG}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
